# -*- coding: utf-8 -*-
"""EDA Project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PeOyh7jgaMTwi5CCmGaR1V0uxC5OpM_E

# Intsalling Important Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""## Reading the CSV File from the Local Disk"""

df = pd.read_csv("studentdata.csv")

"""### Checking the Table containing the Dataset and its Variables"""

df.head()

""" Understanding the size and structure of Dataset before performing data analysis or manipulations."""

df.shape

"""Checking valuable insights into the data's distribution and central tendencies"""

df.describe()

"""Checking the columns we have in dataset to make relation later"""

df.columns

"""Identifying the unique values of every varibale in the Dataset"""

df.nunique()

"""Identifying the Null values of every varibale in the Dataset that can cause distortion in results"""

df.isnull().sum()

"""Dropping unnecessary variables (columns) from a DataFrame which are not so important for results"""

student = df.drop(['school', 'Mjob', 'Fjob', 'reason', 'guardian', 'higher', 'internet', 'romantic', 'health'], axis=1)

"""Checking the table again after dropping the variables"""

student.head()

"""Creating a grid of scatterplots, histograms, and density plots to visualize the relationships between variables in a dataset"""

sns.pairplot(student)

"""Creating Different Graphs to analysis the data and its realtion with other variables. Also check the dependency of one Variable on other."""

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='sex')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 6))
plt.hist(df['age'], bins=10, edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='address')
plt.title('Urban vs. Rural Address Distribution')
plt.xlabel('Address Type')
plt.ylabel('Count')
plt.show()

sns.kdeplot(data=df[['G1', 'G2', 'G3']], fill=True)
plt.xlabel('Grades')
plt.ylabel('Density')
plt.title('Kernel Density Plot of Grades')
plt.show()

sns.violinplot(data=df[['G1', 'G2', 'G3']])
plt.ylabel('Grades')
plt.title('Violin Plot of Grades')
plt.show()

sns.boxplot(data=df[['G1', 'G2', 'G3']])
plt.ylabel('Grades')
plt.title('Box Plot of Grades')
plt.show()

sns.distplot(student['G1'], bins=20)

sns.distplot(student['G2'], bins=20)

sns.distplot(student['G3'], bins=20)

"""# New Section"""